### ISSUE TITLE
Create a `print()` method for analysis objects

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/steppedwedge#1]
Create a `print()` method for analysis objects. Perhaps this could display the following:
1) An estimate and confidence interval for the main effect of interest
2) A note on whether or not the model converged

**Comment by davidearthur** [comment]
I've done this, but we may want to tweak it some.

**Comment by Avi-Kenny** [comment]
Looks great! I'm closing the issue for now and we can tweak in the future if we want.

**Comment by Avi-Kenny** [comment]
Actually, I'm going to re-open the issue. Can we add the following:
* Can we have the first line be a summary of the model? For GEE models, we can say "GEE model with working independence" etc. For mixed models, we can say "Mixed model with random effects for cluster and time"
* The second line can be a summary of the time assumptions. For example 'Exp time: "IT", cal time: "categorical".'.
* Instead of "treatment effect" can we write the estimand name ("TATE" etc.)?
* Let's add the P-value corresponding to the estimated treatment effect. This can't always be extracted from the model object directly, so let's calculate it from the estimate and standard error (via a Z test), which can be done via the following (where `est` is your estimate and `se_est` is your estimated standard error, both corresponding to the estimand of interest):
    * `p_val <- stats::pnorm(est, mean=0, sd=se_est, lower.tail=FALSE)`
* It looks like nothing helpful re: convergence is returned for `geeglm()` (perhaps it throws an error if there is a convergence issue). For now, let's return `NA` in the results object for GEE models and print `"NA"` in the "convergence" field. Note that I removed "convergence2" from the print output because the vignette showed that this was being printed twice (but let's retain it in the results object).

Note that a lot of this will also require modification of the `analyze()` function.
