### ISSUE TITLE
Adjust test dataset to include random time effect

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/steppedwedge#2]
The default mixed model includes a random cluster effect and a so-called "random time effect" (a random intercept corresponding to the cluster-time interaction). Right now, fitting the test dataset (in the vignette) gives a warning, presumably because the underlying dataset was not generated with a random time effect. Let's adjust the test dataset to include this random effect such that the vignette doesn't give this warning.

**Comment by davidearthur** [comment]
I've done this now, but it would probably be good for you to check over the way I did it when you have a chance (in sw_data_example.R).

**Comment by Avi-Kenny** [comment]
Looks great! I made some very minor tweaks.
