### ISSUE TITLE
Minor issue with NCS specification

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/steppedwedge#4]
The file analyze.R currently contains the following line:

```R
indices <- grep("^b[0-9]+$", rownames(summary_ncs$coefficients))
```

I believe this will break if there are 10 or more spline terms (which may be encountered in reality for studies with many time points). Can we test this out and modify accordingly?

**Comment by davidearthur** [comment]
I think it's ok unless I'm misunderstanding something. The grep() code should save the index numbers for all variables that start with "b" and end with any number of digits (with no characters between the "b" and the digits), so it should still select the indices for b10, b11, etc.
e.g. 
![image](https://github.com/user-attachments/assets/478599ea-09d3-45a5-8136-06cc6ea9edb4)

**Comment by Avi-Kenny** [comment]
@davidearthur  yep you're totally right (and better at regexp than me)! My mistake. I'll close this issue. Thanks!
